### ISSUE TITLE
Не по теме, но не знаю, как с вами связаться.)

### ISSUE THREAD

**Issue by alexorex** [iliasam/USB_Photoframe#1]
Прочитав вашу статью на Хабре про самодельный фазовый дальномер, год назад, я её запомнил, а сейчас появилась потребность в чём-то подобном у меня на работе. Можете мне написать на почту alexorex@yandex.ru ?
В кратце - нужно отслеживать положение небольшого движущегося объекта на площадке линейных размеров в несколько десятков метров. С точностью до миллиметров. Есть идея использовать распознавание видео, но тут распознавать достаточно точно - это крайне дорого. Я вспомнил про вашу работу и решил, если поместить генератор в этот объект и приёмники - вокруг площадки, можно очень точно его отслеживать. С точки зрения вычислений - несколько уравнений, а вот аппаратно - не приложу ума.
Не будете добры помочь разобраться?

**Comment by alexorex** [comment]
а по какому вопросу, не напомните ?

Отправлено с iPad

**Comment by iliasam** [comment]
Простите, вы о чем? Вы спрашивали меня про возможность создания системы трекинга объектов, и хотели связаться со мной. Я сейчас закрыл этот issue.

**Comment by alexorex** [comment]
а, это было очень давно, видимо

мы сейчас разрабатываем 3 метода, в неспешном режиме
видео-камерами с машинным зрением, видео-камерами с FPGA, ещё POZYX

что вы можете предложить ? принцип, точность, бюджет

Отправлено с iPad
